FROM arm32v6/node:12-alpine as node_cache

WORKDIR /usr/src/app

# Add package.json
COPY package*.json .

# Restore node modules
RUN npm install

# Add everything else not excluded by .dockerignore
COPY . .

# Build it
RUN npm run build-prod

#2nd stage
FROM arm32v6/node:12-alpine
WORKDIR /usr/src/app
USER root

COPY --from=node_cache /usr/src/app .

# Copy source files, and possibily invalidate so we have to rebuild
COPY . . 

EXPOSE 3000
CMD [ "node", "dist/server.js" ]
