FROM arm32v7/node:8

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY *.js /usr/src/app/
COPY *.json /usr/src/app/
COPY src/ /usr/src/app/src/
COPY www/ /usr/src/app/www/

RUN npm install && \
    npm run build-prod && \
    npm install --save https://github.com/MeisterTR/ioBroker.landroid-s.git

EXPOSE 3000
CMD [ "node", "dist/server.js" ]
